# Generated by Django 2.1.8 on 2019-04-08 04:55

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.utils.recipe_image_file_path),
        ),
    ]
